// <auto-generated />
using System;
using C4iSytemsMobApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace C4iSytemsMobApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251117112139_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("C4iSytemsMobApp.Data.Entity.ClientSiteSmartWandTagsHitLogCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HitLocalDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HitUtcDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelDescription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoggedInClientSiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoggedInGuardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoggedInUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SmartWandId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TagLinkedClientSiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagUId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TagsTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ClientSiteSmartWandTagsHitLogCache");
                });
#pragma warning restore 612, 618
        }
    }
}
