// <auto-generated />
using System;
using C4iSytemsMobApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace C4iSytemsMobApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260122054120_Logactivitydocumentcache")]
    partial class Logactivitydocumentcache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("C4iSytemsMobApp.Data.Entity.ActivityModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActivityModel");
                });

            modelBuilder.Entity("C4iSytemsMobApp.Data.Entity.ClientSiteSmartWandTagsHitLogCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EventDateTimeLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EventDateTimeLocalWithOffset")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EventDateTimeUtcOffsetMinute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventDateTimeZone")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventDateTimeZoneShort")
                        .HasColumnType("TEXT");

                    b.Property<string>("GPScoordinates")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HitLocalDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HitUtcDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoggedInClientSiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoggedInGuardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoggedInUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SmartWandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagUId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagsTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UniqueRecordId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClientSiteSmartWandTagsHitLogCache");
                });

            modelBuilder.Entity("C4iSytemsMobApp.Data.Entity.ClientSiteSmartWandTagsLocal", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientSiteId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FqBypass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsType")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagsTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClientSiteSmartWandTagsLocal");
                });

            modelBuilder.Entity("C4iSytemsMobApp.Data.Entity.OfflineFilesRecords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EventDateTimeLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EventDateTimeLocalWithOffset")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EventDateTimeUtcOffsetMinute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventDateTimeZone")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventDateTimeZoneShort")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FileGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileNameActual")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileNameCache")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileNameWithPathCache")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LogBookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecordLabel")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UniqueRecordId")
                        .HasColumnType("TEXT");

                    b.Property<int>("clientsiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("gps")
                        .HasColumnType("TEXT");

                    b.Property<int>("guardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OfflineFilesRecords");
                });

            modelBuilder.Entity("C4iSytemsMobApp.Data.Entity.PostActivityRequestLocalCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EventDateTimeLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EventDateTimeLocalWithOffset")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EventDateTimeUtcOffsetMinute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventDateTimeZone")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventDateTimeZoneShort")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNewGuard")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UniqueRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("activityString")
                        .HasColumnType("TEXT");

                    b.Property<int>("clientsiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("gps")
                        .HasColumnType("TEXT");

                    b.Property<int>("guardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("scanningType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("systemEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tagUID")
                        .HasColumnType("TEXT");

                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PostActivityRequestLocalCache");
                });
#pragma warning restore 612, 618
        }
    }
}
