// <auto-generated />
using System;
using C4iSytemsMobApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace C4iSytemsMobApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("C4iSytemsMobApp.Data.Entity.ClientSiteSmartWandTagsHitLogCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GPScoordinates")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HitLocalDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HitUtcDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoggedInClientSiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoggedInGuardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoggedInUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SmartWandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagUId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagsTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UniqueRecordId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClientSiteSmartWandTagsHitLogCache");
                });

            modelBuilder.Entity("C4iSytemsMobApp.Data.Entity.ClientSiteSmartWandTagsLocal", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientSiteId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FqBypass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsType")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagsTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClientSiteSmartWandTagsLocal");
                });
#pragma warning restore 612, 618
        }
    }
}
